# Generated by Django 4.1 on 2022-09-04 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article_tittle',
            new_name='article_title',
        ),
    ]
